model:
  fc_dim_branch: 512
  fc_dim: 512
  N_layer: 3
  n_head: 1

train:
  epochs: 200
  coor_sampling_size: 100
  batchsize: 10
  coor_sampling_freq: 3
  base_lr: 0.0001
  bc_weight: 10
  visual_freq: 20
